const char wifi_provisioning_content[] =
  "\r\n<!DOCTYPE html>"
  "\r\n<html lang=\"en\">"
  "\r\n<head>"
  "\r\n<meta charset=\"UTF-8\">"
  "\r\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
  "\r\n<title>Silabs Wi-Fi Network Provisioning</title>"
  "\r\n<style><!--  -->"
  "\r\nbody {"
  "\r\nfont-family: Arial, sans-serif;"
  "\r\nmargin: 0;"
  "\r\npadding: 0;"
  "\r\ndisplay: flex;"
  "\r\njustify-content: center;"
  "\r\nalign-items: center;"
  "\r\nheight: 100vh;"
  "\r\nbackground-color: #f0f0f0;"
  "\r\n}"
  "\r\n#scan-form {"
  "\r\ntext-align: center;"
  "\r\npadding: 20px;"
  "\r\nborder: 1px solid #ccc;"
  "\r\nborder-radius: 8px;"
  "\r\nbackground-color: #fff;"
  "\r\n}"
  "\r\ninput[type=\"submit\"] {"
  "\r\nwidth: 100%;"
  "\r\npadding: 10px;"
  "\r\nmargin: 10px 0;"
  "\r\nborder: none;"
  "\r\nborder-radius: 5px;"
  "\r\nbackground-color: #007bff;"
  "\r\ncolor: #fff;"
  "\r\ncursor: pointer;"
  "\r\n}"
  "\r\ninput[type=\"submit\"]:hover {"
  "\r\nbackground-color: #0056b3;"
  "\r\n}"
  "\r\n#heading {"
  "\r\nmargin-bottom: 20px;"
  "\r\nwidth: 100%;"
  "\r\n}"
  "\r\n.form-row {"
  "\r\ndisplay: flex;"
  "\r\njustify-content: space-between;"
  "\r\nalign-items: center;"
  "\r\nmargin: 10px 0;"
  "\r\n}"
  "\r\n.form-row label {"
  "\r\nwidth: 100px;"
  "\r\ntext-align: right;"
  "\r\nmargin-right: 10px;"
  "\r\nwhite-space: nowrap;"
  "\r\n}"
  "\r\n.form-row input,"
  "\r\n.form-row select {"
  "\r\nflex: 2;"
  "\r\n}"
  "\r\n#scan-results {"
  "\r\n    text-align: center;"
  "\r\n    padding: 20px;"
  "\r\n    border: 1px solid #ccc;"
  "\r\n    border-radius: 8px;"
  "\r\n    background-color: #fff;"
  "\r\n    margin-top: 20px;"
  "\r\n}"
  "\r\n#connect-button {"
  "\r\n    margin-top: 20px;"
  "\r\n}"
  "\r\n#password-input {"
  "\r\n    width: 93%;"
  "\r\n    padding: 10px;"
  "\r\n    margin: 10px 0;"
  "\r\n    border: none;"
  "\r\n    border-radius: 5px;"
  "\r\n    font-size: 16px; /* Optional: You can adjust the font size */"
  "\r\n}"
  "\r\n</style>"
  "\r\n</head>"
  "\r\n<body>"
  "\r\n<form id=\"scan-form\" action=\"/scan\" method=\"get\">"
  "\r\n<h3 id=\"heading\">Silabs Wi-Fi Network Provisioning</h3>"
  "\r\n<input type=\"submit\" value=\"Scan\">"
  "\r\n<div id=\"scan-results\"></div>"
  "\r\n<input type=\"submit\" value=\"Connect\" id=\"connect-button\">"
  "\r\n<input type=\"password\" placeholder=\"Enter password\" id=\"password-input\"> <!-- Added password input -->"
  "\r\n</form>"
  "\r\n<script>"
  "\r\ndocument.getElementById('scan-form').addEventListener('submit', function (event) {"
  "\r\n    event.preventDefault();"
  "\r\n    var xhr = new XMLHttpRequest();"
  "\r\n    xhr.open('GET', '/scan', true);"
  "\r\n    xhr.setRequestHeader('Content-Type', 'application/json');"
  "\r\n    xhr.onload = function() {"
  "\r\n        if (xhr.status === 200) {"
  "\r\n            var scanResults = JSON.parse(xhr.responseText);"
  "\r\n            var scanResultsTable = document.createElement('table');"
  "\r\n            scanResultsTable.style.borderCollapse = \"collapse\";"
  "\r\n            scanResultsTable.style.width = \"100%\";"
  "\r\n"
  "\r\n            // Clear existing table"
  "\r\n            document.getElementById('scan-results').innerHTML = \"\";"
  "\r\n"
  "\r\n            // Create table header"
  "\r\n            var tableHeader = document.createElement('tr');"
  "\r\n            var headerColumns = [\"Select\", \"SSID\", \"Security Type\", \"Channel\", \"RSSI\"];"
  "\r\n            headerColumns.forEach(function(column) {"
  "\r\n                var th = document.createElement('th');"
  "\r\n                th.textContent = column;"
  "\r\n                th.style.border = \"1px solid #ccc\";"
  "\r\n                th.style.padding = \"8px\";"
  "\r\n                th.style.backgroundColor = \"#f0f0f0\";"
  "\r\n                tableHeader.appendChild(th);"
  "\r\n            });"
  "\r\n            scanResultsTable.appendChild(tableHeader);"
  "\r\n"
  "\r\n            // Create table rows"
  "\r\n            scanResults.scan_results.forEach(function(result) {"
  "\r\n                var tableRow = document.createElement('tr');"
  "\r\n"
  "\r\n                // Add select radio button"
  "\r\n                var selectRadio = document.createElement('input');"
  "\r\n                selectRadio.type = \"radio\";"
  "\r\n                selectRadio.name = \"selectedSSID\";"
  "\r\n                selectRadio.value = result.ssid;"
  "\r\n                var selectRadioCell = document.createElement('td');"
  "\r\n                selectRadioCell.appendChild(selectRadio);"
  "\r\n                selectRadioCell.style.border = \"1px solid #ccc\"; // Added border style"
  "\r\n                tableRow.appendChild(selectRadioCell);"
  "\r\n"
  "\r\n                var rowData = [result.ssid, result.security_type, result.channel, result.rssi];"
  "\r\n                rowData.forEach(function(data, index) {"
  "\r\n                    var td = document.createElement('td');"
  "\r\n                    td.textContent = data;"
  "\r\n                    td.style.border = \"1px solid #ccc\";"
  "\r\n                    td.style.padding = \"8px\";"
  "\r\n                    tableRow.appendChild(td);"
  "\r\n                });"
  "\r\n"
  "\r\n                scanResultsTable.appendChild(tableRow);"
  "\r\n            });"
  "\r\n"
  "\r\n            // Clear existing scan-results div"
  "\r\n            var scanResultsDiv = document.getElementById('scan-results');"
  "\r\n            scanResultsDiv.innerHTML = \"\";"
  "\r\n"
  "\r\n            // Append the table to the scan-results div"
  "\r\n            scanResultsDiv.appendChild(scanResultsTable);"
  "\r\n        };"
  "\r\n    };"
  "\r\n    xhr.send();"
  "\r\n});"
  "\r\n"
  "\r\ndocument.getElementById('connect-button').addEventListener('click', function (event) {"
  "\r\n    event.preventDefault();"
  "\r\n    var selectedSSID = document.querySelector('input[name=\"selectedSSID\"]:checked');"
  "\r\n    if (selectedSSID) {"
  "\r\n        var ssid = selectedSSID.value;"
  "\r\n        var password = document.getElementById('password-input').value;"
  "\r\n        var securityType = selectedSSID.parentElement.nextElementSibling.nextElementSibling.textContent; // Get "
  "the text content of the next sibling element"
  "\r\n        var xhr = new XMLHttpRequest();"
  "\r\n        xhr.open('POST', '/connect', true);"
  "\r\n        xhr.setRequestHeader('Content-Type', 'application/json');"
  "\r\n        var data = {"
  "\r\n            ssid: ssid,"
  "\r\n            passphrase: password,"
  "\r\n            security_type: securityType"
  "\r\n        };"
  "\r\n        xhr.send(JSON.stringify(data));"
  "\r\n        document.getElementById('scan-form').style.display = 'none'; // Hide the scan form"
  "\r\n        document.getElementById('scan-results').innerHTML = 'Connecting ...'; // Show \"Connecting ...\" message"
  "\r\n    } else {"
  "\r\n        alert('Please select a network to connect.');"
  "\r\n    }"
  "\r\n});"
  "\r\n</script>"
  "\r\n</body>"
  "\r\n</html>";
