/*******************************************************************************
 * @file  ble_commands_compat.c
 * @brief Back-compat weak shims for BLE AT-command handlers renamed between
 *        wiseconnect3_sdk 4.0.x and 4.1.0.
 *******************************************************************************
 *
 * The autogenerated console command database references the new (4.1.0)
 * handler names. The weak default for each new name forwards to the
 * corresponding old name, so application sources preserved from the
 * previous SDK (which still define the old name as a strong symbol)
 * continue to link without source edits.
 *
 * The weak default for each old name returns SL_STATUS_NOT_SUPPORTED so
 * fresh 4.1.0 projects that do not supply either name still link cleanly.
 *
 * If the application supplies a strong definition for either name, that
 * strong symbol overrides the corresponding weak default below.
 *
 ******************************************************************************/

#include "cmsis_compiler.h"
#include "console_types.h"
#include "sl_constants.h"
#include "sl_status.h"

sl_status_t ble_max_per_command_handler(console_args_t *arguments);
sl_status_t ble_max_peripherals_command_handler(console_args_t *arguments);

/* 4.0.x: ble_max_per_command_handler
 * 4.1.0: ble_max_peripherals_command_handler */
__WEAK sl_status_t ble_max_per_command_handler(console_args_t *arguments)
{
  UNUSED_PARAMETER(arguments);
  return SL_STATUS_NOT_SUPPORTED;
}

__WEAK sl_status_t ble_max_peripherals_command_handler(console_args_t *arguments)
{
  return ble_max_per_command_handler(arguments);
}
