/*******************************************************************************
* @file  smp_init.c
* @brief SMP (Security Manager Protocol) Initialization
*******************************************************************************
* # License
* <b>Copyright 2020 Silicon Laboratories Inc. www.silabs.com</b>
*******************************************************************************
*
* The licensor of this software is Silicon Laboratories Inc. Your use of this
* software is governed by the terms of Silicon Labs Master Software License
* Agreement (MSLA) available at
* www.silabs.com/about-us/legal/master-software-license-agreement. This
* software is distributed to you in Source Code format and is governed by the
* sections of the MSLA applicable to Source Code.
*
******************************************************************************/

// Standard C library
#include <stdio.h>   // printf() - debug messages
#include <stdbool.h> // bool type
#include <string.h>  // memcpy()
#include <inttypes.h>

// SMP Component headers
#include <smp_config.h> // SMP configuration - resolved via -I: config/ble_config/ (user override) first, then component inc/
#include "smp.h"        // SMP types and API (includes gap.h)

// BLE SDK APIs
#include "rsi_ble.h"            // rsi_ble_set_smp_pairing_cap_data()
#include "rsi_bt_common_apis.h" // RSI_FAILURE, RSI_SUCCESS

// BLE SDK Configuration (fallback if not defined in smp_config.h)
#include "rsi_ble_common_config.h" // RSI_BLE_SMP_IO_CAPABILITY (fallback)

// Status codes
#include "sl_si91x_status.h" // SL_STATUS_OK

/*=======================================================================*/
//! External Variable Declarations
/*=======================================================================*/

// Parsed configuration (defined in BLE Unified)
extern rsi_parsed_conf_t rsi_parsed_conf;

/*=======================================================================*/
//! External Function Declarations
/*=======================================================================*/

// Wrapper function generated by framework
extern void sl_btc_ble_smp_register_callbacks_wrapper(void);

/*=======================================================================*/
//! SMP Initialization Function
//! EXTRACTED FROM: ble_unified_app.c lines 1554-1566
/*=======================================================================*/

/**
 * @brief Initialize SMP component
 * @return int32_t - SL_STATUS_OK on success, error code otherwise
 * 
 * @details Initializes SMP pairing capabilities, registers callbacks,
 *          and sets up SMP-specific connection configuration.
 * 
 * EXTRACTED FROM: ble_unified_app.c lines 1554-1566
 */
int32_t ble_smp_init(void)
{
  int32_t status;
  rsi_ble_set_smp_pairing_capabilty_data_t smp_capabilities;

  printf("\r\n Initializing SMP...\r\n");

  // Step 1: Register SMP callbacks
  sl_btc_ble_smp_register_callbacks_wrapper();

  // Step 2: Initialize SMP-specific connection state (from smp_utilities.c)
  // Function: rsi_ble_smp_default_init()
  rsi_ble_smp_default_init();

  // Step 3: Initialize SMP-specific connection buffer configuration (from smp_utilities.c)
  // Function: rsi_ble_smp_initialize_conn_config()
  status =
    rsi_ble_smp_initialize_conn_config((rsi_ble_conn_config_t *)&rsi_parsed_conf.rsi_ble_config.rsi_ble_conn_config);
  if (status != RSI_SUCCESS) {
    printf("\r\n Failed to initialize SMP conn config\r\n");
    return status;
  }

  // Step 4: Configure SMP pairing capabilities (extracted from ble_unified_app.c)
  smp_capabilities.io_capability        = RSI_BLE_SMP_IO_CAPABILITY;
  smp_capabilities.oob_data_flag        = LOCAL_OOB_DATA_FLAG_NOT_PRESENT;
  smp_capabilities.enc_key_size         = MAXIMUM_ENC_KEY_SIZE_16;
  smp_capabilities.ini_key_distribution = INITIATOR_KEYS_TO_DIST;
  smp_capabilities.rsp_key_distribution = RESPONDER_KEYS_TO_DIST;
  smp_capabilities.auth_req             = AUTH_REQ_BITS;

  status = rsi_ble_set_smp_pairing_cap_data(&smp_capabilities);
  if (status != RSI_SUCCESS) {
    printf("\n rsi_ble_set_smp_pairing_cap_data failed: 0x%" PRIX32 "\n", status);
    return status;
  }

  printf("\r\n SMP initialized successfully\r\n");
  return SL_STATUS_OK;
}
