const char sensor_webserver_content[] =
  "\r\n<!DOCTYPE html>"
  "\r\n<html lang=\"en\">"
  "\r\n<head>"
  "\r\n<meta charset=\"UTF-8\">"
  "\r\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
  "\r\n<title>Embedded Sensor Demo</title>"
  "\r\n<style><!--  -->"
  "\r\nbody {"
  "\r\nfont-family: Arial, sans-serif;"
  "\r\nmargin: 0;"
  "\r\npadding: 0;"
  "\r\ndisplay: flex;"
  "\r\njustify-content: center;"
  "\r\nalign-items: center;"
  "\r\nheight: 100vh;"
  "\r\nbackground-color: #f0f0f0;"
  "\r\n}"
  "\r\n#refresh-form {"
  "\r\ntext-align: center;"
  "\r\npadding: 20px;"
  "\r\nborder: 1px solid #ccc;"
  "\r\nborder-radius: 8px;"
  "\r\nbackground-color: #fff;"
  "\r\n}"
  "\r\ninput[type=\"submit\"] {"
  "\r\nwidth: 100%;"
  "\r\npadding: 10px;"
  "\r\nmargin: 10px 0;"
  "\r\nborder: none;"
  "\r\nborder-radius: 5px;"
  "\r\nbackground-color: #007bff;"
  "\r\ncolor: #fff;"
  "\r\ncursor: pointer;"
  "\r\n}"
  "\r\ninput[type=\"submit\"]:hover {"
  "\r\nbackground-color: #0056b3;"
  "\r\n}"
  "\r\n#heading {"
  "\r\nmargin-bottom: 20px;"
  "\r\nwidth: 100%;"
  "\r\n}"
  "\r\n.form-row {"
  "\r\ndisplay: flex;"
  "\r\njustify-content: space-between;"
  "\r\nalign-items: center;"
  "\r\nmargin: 10px 0;"
  "\r\n}"
  "\r\n.form-row label {"
  "\r\nwidth: 100px;"
  "\r\ntext-align: right;"
  "\r\nmargin-right: 10px;"
  "\r\nwhite-space: nowrap;"
  "\r\n}"
  "\r\n.form-row input,"
  "\r\n.form-row select {"
  "\r\nflex: 2;"
  "\r\n}"
  "\r\n#sensor-data {"
  "\r\n    text-align: center;"
  "\r\n    padding: 20px;"
  "\r\n    border: 1px solid #ccc;"
  "\r\n    border-radius: 8px;"
  "\r\n    background-color: #fff;"
  "\r\n    margin-top: 20px;"
  "\r\n}"
  "\r\n</style>"
  "\r\n</head>"
  "\r\n<body>"
  "\r\n<form id=\"refresh-form\" action=\"/scan\" method=\"get\">"
  "\r\n<h3 id=\"heading\">Embedded Sensor Demo</h3>"
  "\r\n<input type=\"submit\" value=\"Refresh\">"
  "\r\n<div id=\"sensor-data\">"
  "\r\n<table>"
  "\r\n    <tr>"
  "\r\n        <th style=\"text-align: left;\">Sensor</th>"
  "\r\n        <th style=\"text-align: left;\">Data</th>"
  "\r\n        <th style=\"text-align: center;\">Value</th>"
  "\r\n        <th style=\"text-align: center;\">Unit</th>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td style=\"text-align: left;\">LED</td>"
  "\r\n        <td style=\"text-align: left;\">Red</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"red-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">---</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td></td>"
  "\r\n        <td style=\"text-align: left;\">Green</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"green-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">---</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td></td>"
  "\r\n        <td style=\"text-align: left;\">Blue</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"blue-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">---</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td style=\"text-align: left;\">Light</td>"
  "\r\n        <td style=\"text-align: left;\">Ambient</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"ambient-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">Lux</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td></td>"
  "\r\n        <td style=\"text-align: left;\">White</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"white-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">Lux</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td style=\"text-align: left;\">Temperature</td>"
  "\r\n        <td style=\"text-align: left;\">Temperature</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"temperature-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">°C</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td style=\"text-align: left;\">Humidity</td>"
  "\r\n        <td style=\"text-align: left;\">Humidity</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"humidity-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">%</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td style=\"text-align: left;\">Accelerometer</td>"
  "\r\n        <td style=\"text-align: left;\">X</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"accelerometer-x-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">---</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td></td>"
  "\r\n        <td style=\"text-align: left;\">Y</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"accelerometer-y-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">---</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td></td>"
  "\r\n        <td style=\"text-align: left;\">Z</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"accelerometer-z-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">---</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td style=\"text-align: left;\">Gyroscope</td>"
  "\r\n        <td style=\"text-align: left;\">X</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"gyroscope-x-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">---</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td></td>"
  "\r\n        <td style=\"text-align: left;\">Y</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"gyroscope-y-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">---</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td></td>"
  "\r\n        <td style=\"text-align: left;\">Z</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"gyroscope-z-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">---</td>"
  "\r\n    </tr>"
  "\r\n    <tr>"
  "\r\n        <td style=\"text-align: left;\">Microphone</td>"
  "\r\n        <td style=\"text-align: left;\">Sound Level</td>"
  "\r\n        <td style=\"text-align: center;\" id=\"microphone-value\">---</td>"
  "\r\n        <td style=\"text-align: center;\">Decibel</td>"
  "\r\n    </tr>"
  "\r\n</table>"
  "\r\n</div>"
  "\r\n</form>"
  "\r\n<script>"
  "\r\ndocument.getElementById('refresh-form').addEventListener('submit', function (event) {"
  "\r\n    event.preventDefault();"
  "\r\n"
  "\r\n    var xhr = new XMLHttpRequest();"
  "\r\n    xhr.open('GET', '/all_sensors', true);"
  "\r\n    xhr.setRequestHeader('Content-Type', 'application/json');"
  "\r\n    xhr.onload = function() {"
  "\r\n        if (xhr.status === 200) {"
  "\r\n            var response = JSON.parse(xhr.responseText);"
  "\r\n            var redValue = document.getElementById('red-value');"
  "\r\n            var greenValue = document.getElementById('green-value');"
  "\r\n            var blueValue = document.getElementById('blue-value');"
  "\r\n            var ambientValue = document.getElementById('ambient-value');"
  "\r\n            var whiteValue = document.getElementById('white-value');"
  "\r\n            var temperatureValue = document.getElementById('temperature-value');"
  "\r\n            var humidityValue = document.getElementById('humidity-value');"
  "\r\n            var accelerometerXValue = document.getElementById('accelerometer-x-value');"
  "\r\n            var accelerometerYValue = document.getElementById('accelerometer-y-value');"
  "\r\n            var accelerometerZValue = document.getElementById('accelerometer-z-value');"
  "\r\n            var gyroscopeXValue = document.getElementById('gyroscope-x-value');"
  "\r\n            var gyroscopeYValue = document.getElementById('gyroscope-y-value');"
  "\r\n            var gyroscopeZValue = document.getElementById('gyroscope-z-value');"
  "\r\n            var microphoneValue = document.getElementById('microphone-value');"
  "\r\n"
  "\r\n            redValue.textContent = response.led.red;"
  "\r\n            greenValue.textContent = response.led.green;"
  "\r\n            blueValue.textContent = response.led.blue;"
  "\r\n"
  "\r\n            ambientValue.textContent = response.light.ambient_light_lux;"
  "\r\n            whiteValue.textContent = response.light.white_light_lux;"
  "\r\n"
  "\r\n            temperatureValue.textContent = response.temperature.temperature_celcius;"
  "\r\n"
  "\r\n            humidityValue.textContent = response.humidity.humidity_percentage;"
  "\r\n"
  "\r\n            accelerometerXValue.textContent = response.accelerometer.x;"
  "\r\n            accelerometerYValue.textContent = response.accelerometer.y;"
  "\r\n            accelerometerZValue.textContent = response.accelerometer.z;"
  "\r\n"
  "\r\n            gyroscopeXValue.textContent = response.gyroscope.x;"
  "\r\n            gyroscopeYValue.textContent = response.gyroscope.y;"
  "\r\n            gyroscopeZValue.textContent = response.gyroscope.z;"
  "\r\n"
  "\r\n            microphoneValue.textContent = response.microphone.microphone_decibel;"
  "\r\n        };"
  "\r\n    };"
  "\r\n    xhr.send();"
  "\r\n});"
  "\r\n</script>"
  "\r\n</body>"
  "\r\n</html>";
