/*******************************************************************************
* @file  ble_unified_app.h
* @brief BLE Unified Component - Public API
*******************************************************************************
* # License
* <b>Copyright 2025 Silicon Laboratories Inc. www.silabs.com</b>
*******************************************************************************
*
* The licensor of this software is Silicon Laboratories Inc. Your use of this
* software is governed by the terms of Silicon Labs Master Software License
* Agreement (MSLA) available at
* www.silabs.com/about-us/legal/master-software-license-agreement. This
* software is distributed to you in Source Code format and is governed by the
* sections of the MSLA applicable to Source Code.
*
******************************************************************************/

#ifndef BLE_UNIFIED_APP_H
#define BLE_UNIFIED_APP_H

#include <stdint.h>
#include <ble_unified_app_config.h> // resolved via -I: autogen/ (SLC-generated template)
#include "sl_wifi_device.h"

/**
 * @brief BLE unified task entry point
 * 
 * This function initializes the BLE unified framework and enters the event loop.
 * It never returns.
 */
void rsi_ble_main_app_task(void);

/**
 * @brief BLE initialization hook (autogenerated in ble_init_hook.c)
 * 
 * Calls protocol init functions contributed by selected components.
 */
int32_t ble_init_hook(void);

/**
 * @brief Set BLE feature bitmaps on device configuration (autogenerated in bt_bitmap.c).
 * 
 * ORs component-contributed BLE config into boot_config.ble_feature_bit_map and
 * boot_config.ble_ext_feature_bit_map. Call before sl_si91x_driver_init() or equivalent.
 * @param[in,out] ble_device_config  Device configuration to update.
 */
void set_bt_ble_bitmaps(sl_wifi_device_configuration_t *ble_device_config);

#endif // BLE_UNIFIED_APP_H
