/*******************************************************************************
* @file  ble_unified_app.c
* @brief BLE Unified Component - Minimal Orchestration Layer
*******************************************************************************
* # License
* <b>Copyright 2025 Silicon Laboratories Inc. www.silabs.com</b>
*******************************************************************************
*
* The licensor of this software is Silicon Laboratories Inc. Your use of this
* software is governed by the terms of Silicon Labs Master Software License
* Agreement (MSLA) available at
* www.silabs.com/about-us/legal/master-software-license-agreement. This
* software is distributed to you in Source Code format and is governed by the
* sections of the MSLA applicable to Source Code.
*
******************************************************************************/

/**
 * @brief BLE Unified Component - Minimal orchestration layer for BLE protocol components
 * 
 * This component provides:
 * - rsi_ble_main_app_task() with event loop setup and power save
 * 
 * ble_init_hook() and weak protocol init stubs are autogenerated (ble_init_hook.c).
 * Protocol components override the weak stubs when present.
 */

#include "sl_constants.h"
#include "sl_wifi.h"
#include "cmsis_os2.h"
#include <ble_unified_app_config.h> // resolved via -I: autogen/ (SLC-generated template)
#include "ble_unified_app.h"        // Component API header
#include "event_loop.h"
#include "ble_event_hdlr_auto_gen.h"
#include "rsi_common_apis.h"
#include "rsi_bt_common_apis.h"
#include <stdio.h>
#include <inttypes.h>

extern generic_task_cb_t ble_generic_cb;
extern generic_event_handler_lut_entry_t ble_events_lut[];

/*=======================================================================*/
//! Powersave configurations
/*=======================================================================*/

#if ENABLE_NWP_POWER_SAVE
#if !WLAN_TASK_ENABLE
sl_wifi_performance_profile_v2_t wifi_profile = { .profile = ASSOCIATED_POWER_SAVE_LOW_LATENCY };
#endif

#endif

/*==============================================*/
/**
 * @fn         rsi_ble_main_app_task
 * @brief      BLE main application task - event loop orchestration
 * @return     void
 * @section description
 * This function:
 * 1. Configures event loop control block
 * 2. Configures power save (if enabled)
 * 3. Enters unified event loop (never returns)
 * 
 * NOTE: WiFi/device initialization should be done by the application
 * before calling this function.
 */
void rsi_ble_main_app_task(void)
{
  int32_t status;
  UNUSED_PARAMETER(status);
  printf("\r\n BLE Main Task Invoked\r\n");

  // Configure event loop control block
  ble_generic_cb.init_hook            = ble_init_hook;
  ble_generic_cb.commands_handler_lut = NULL;
  ble_generic_cb.events_handler_lut   = ble_events_lut;
  ble_generic_cb.max_num_events       = max_ble_event_id;
  ble_generic_cb.max_num_commands     = 0;

#if ENABLE_NWP_POWER_SAVE
  printf("\r\n Initiating power save mode\r\n");

  // Initiating power save in BLE mode
  status = rsi_bt_power_save_profile(PSP_MODE, PSP_TYPE);
  if (status != RSI_SUCCESS) {
    printf("\r\n Failed to initiate BLE power save: 0x%" PRIX32 "\r\n", status);
    return;
  }

#if !WLAN_TASK_ENABLE
  // Initiating power save in BLE only mode, for coex mode, wifi power save is called in wifiapp.c
  status = sl_wifi_set_performance_profile_v2(&wifi_profile);
  if (status != SL_STATUS_OK) {
    printf("\r\n Failed to initiate Wi-Fi power save: 0x%" PRIX32 "\r\n", status);
    return;
  }
#endif
  printf("\r\n Module is in power save\r\n");
#endif

  // Enter unified event loop (never returns)
  rsi_app_common_event_loop(&ble_generic_cb);
}
