/*******************************************************************************
* @file  wifiuser.pem.h
* @brief
*******************************************************************************
* # License
* <b>Copyright 2023 Silicon Laboratories Inc. www.silabs.com</b>
*******************************************************************************
*
* The licensor of this software is Silicon Laboratories Inc. Your use of this
* software is governed by the terms of Silicon Labs Master Software License
* Agreement (MSLA) available at
* www.silabs.com/about-us/legal/master-software-license-agreement. This
* software is distributed to you in Source Code format and is governed by the
* sections of the MSLA applicable to Source Code.
*
******************************************************************************/

#pragma once

const unsigned char wifiuser[] = "-----BEGIN PRIVATE KEY-----\n"
                                 "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDQ3X08kE4S7AjR\n"
                                 "Hj8/MTpvVLTVUiWY7XWaEm+b03+5AG0MunKjC74olRWiXW2y3WrwYIOmO0UOjHky\n"
                                 "Fu2AWCgkcSD0JZxEOtmn66QAGW6tZhvf3ChAbQAdw9qLEHVTVJohAQjil3oqSmpu\n"
                                 "e4y2+0doZGSwDbKz9wdXmIN3acTXRol4e0N8QaziLxv/8P081U0TJ0AnssIszCX8\n"
                                 "APDANiiAI1zqprXRxPk3HhjT6s3bbEDfrZCjx2AWBpR+ogXgm8uIoXQ2IySjdkgS\n"
                                 "Mh19hl+00ZKdJwC4PNdsxUdJW9wn8WPqMjTHSJyJMZOH/8C0JIEy3VcwQKJ1AgkN\n"
                                 "8QIMAtPZAgMBAAECggEAbPM8gr0bnM83Ai5u+32oZ66d7bC+H/muIMKBKZ23wD8y\n"
                                 "ozMW3WogtXafJGTr9iN9xwnxYmMEcMRh6/j9xrc1qVzBvdlonEa+htNqZwrdKuJa\n"
                                 "o/lpncG+D8i8VVIugVteUt0BT4GInkrXHe6gxkppQ1ErHJLopuuzDsRlv4KSxV/5\n"
                                 "8gMBlsVRBqfbsnb/uTi+7bfnL8CelZ52YORHedz8L6iEgw6I/ASNnoaF/Fz1aP39\n"
                                 "/2QQkUdYTKkC9bbHFx+JHXZRNVIffXQVhfcCDXHxAnvoajyfIQvEznK8J5NuEm0u\n"
                                 "RPyPwOipQryBEAISZNE94j689IAl+SRyjrEH95jU6QKBgQD74Vs/YJv/h29Qmnd4\n"
                                 "jXIFogUTbYn1FDpHJts5BS04mm8dVmhk0wHkIdlY8DlKvSF+u/+QHz+jtGH/3uRL\n"
                                 "fWmo6LxcFU5eH7XYjio0YWP8JbWYQTCmq9a4JECnQa3yqFbcWGC//buUluQagzp2\n"
                                 "pQ3LhXKxLLSj12G96DXjPo5p8wKBgQDUSAZkwWtrKCaQNI4Qr/u+IVw/khj/fc5F\n"
                                 "suASiNBed4OKz6n0epCCE6o6qdDM9GvOEMsaORPJtffLhhpHfErcPZ7sKKdzBYts\n"
                                 "0c1KeKWJwwrSnAaTk8DacqbIa5u3wuKrBMZK+c2nscyF8Jpv+Uj7Wo9NjRJGGxHG\n"
                                 "lBGbYCmSAwKBgBUdgT7A5JL5UZWaPWW3xdU/DdnhFu2asoAAe+Q90Nqr56C3+6xo\n"
                                 "HAJ56/SOvt7LGCG9tODqHbWli4mdr9m8O71TNWcqyhUN53quAE+/0lfy+VQ4MtHm\n"
                                 "Gev57gmXcfOjtRRnvEScCrucIqcuVRpZH9zt5P2BV+tcRO9cphfUyK+NAoGAC82l\n"
                                 "bVzD2EV3P3VsoMjoOn4oXvCEq1AXdBCqHN22mEoU6lb5oDpgZpspT/G5Rmwgwmh0\n"
                                 "opSh4QlZKdvfAjKLBwv2FjN8fAzG39oajBWBPtO1elhqlTIV+w987o/tLJ6Nc+zk\n"
                                 "Ca8yHCzqrlfefnNh93fll+5MIdHHfz8ka3tBVHkCgYBb86Vrpf3OKRaZCEnXdcLi\n"
                                 "IgweD95iiKzlEdOrhU4/u1+31JLiCC57fXDmP6WPkLXYW1USOXQSfUbEy5c718dP\n"
                                 "kaZX6AkHJdMkGYvGda9wwCxxLSQ8r/wpckbr84Mr3OKJQAXdzya7RFf1FsBRbbw3\n"
                                 "ATz8Z/ROLNtdkhqgrRgqFw==\n"
                                 "-----END PRIVATE KEY-----\n"
                                 "-----BEGIN CERTIFICATE-----\n"
                                 "MIIDzDCCArSgAwIBAgIUHOt6O0IIpIzDo3IMdEKw7e46rrgwDQYJKoZIhvcNAQEL\n"
                                 "BQAwcDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFDASBgNVBAcM\n"
                                 "C1NhbnRhIENsYXJhMRcwFQYDVQQKDA5XaS1GaSBBbGxpYW5jZTEdMBsGA1UEAwwU\n"
                                 "V0ZBIFJvb3QgQ2VydGlmaWNhdGUwHhcNMjAwNzMwMTgwMTQ5WhcNMzAwNzI4MTgw\n"
                                 "MTQ5WjBcMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEXMBUGA1UE\n"
                                 "CgwOV2ktRmkgQWxsaWFuY2UxHzAdBgNVBAMMFkNsaWVudCBDZXJ0aWZpY2F0ZSBJ\n"
                                 "REwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDQ3X08kE4S7AjRHj8/\n"
                                 "MTpvVLTVUiWY7XWaEm+b03+5AG0MunKjC74olRWiXW2y3WrwYIOmO0UOjHkyFu2A\n"
                                 "WCgkcSD0JZxEOtmn66QAGW6tZhvf3ChAbQAdw9qLEHVTVJohAQjil3oqSmpue4y2\n"
                                 "+0doZGSwDbKz9wdXmIN3acTXRol4e0N8QaziLxv/8P081U0TJ0AnssIszCX8APDA\n"
                                 "NiiAI1zqprXRxPk3HhjT6s3bbEDfrZCjx2AWBpR+ogXgm8uIoXQ2IySjdkgSMh19\n"
                                 "hl+00ZKdJwC4PNdsxUdJW9wn8WPqMjTHSJyJMZOH/8C0JIEy3VcwQKJ1AgkN8QIM\n"
                                 "AtPZAgMBAAGjcjBwMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFJgjVzYiNkdDhvpU\n"
                                 "tK7D0vqa3NzgMB8GA1UdIwQYMBaAFK4Yy7ECaJyxVecdQF8XTwLcSxquMBMGA1Ud\n"
                                 "JQQMMAoGCCsGAQUFBwMCMAsGA1UdDwQEAwIF4DANBgkqhkiG9w0BAQsFAAOCAQEA\n"
                                 "iGC0RDnySgq/Mbbhc2RZEHZzWkBPPl2/qhWEO7XRGP4Zk45RbFNglbCQhzEFRsFq\n"
                                 "sEx3xLfLpK+yGhi4tvlWipxPiGREVHn7qV6xnrMK/oN17BeBjdzZR1t3GDxTWfcQ\n"
                                 "PrNWFNvptIAqd0mfBg6sSlFK6L8oRCzD1pg6x8Jvdx2o11bvz/VVUM3xhTODFDro\n"
                                 "uwuC62pLtMUoJnhBdB/GN7et4Xf/nuwfw0lp8aAn0wT1xMQwk+LTPX2DVzRiOLNR\n"
                                 "8gnjgjfFNmQzcZ4VdKviujytVDzqgwMyjbQBhwbL4HFPPrk2iArOlqTctAmMId7R\n"
                                 "Kiwu3nJJjz2Re71qTJyLfQ==\n"
                                 "-----END CERTIFICATE-----\n"
                                 "-----BEGIN CERTIFICATE-----\n"
                                 "MIIEGjCCAwKgAwIBAgIUNJqZbmEwU+HDER28jLqWcB09dKAwDQYJKoZIhvcNAQEL\n"
                                 "BQAwcDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFDASBgNVBAcM\n"
                                 "C1NhbnRhIENsYXJhMRcwFQYDVQQKDA5XaS1GaSBBbGxpYW5jZTEdMBsGA1UEAwwU\n"
                                 "V0ZBIFJvb3QgQ2VydGlmaWNhdGUwHhcNMjAwNzMwMTgwMTQ5WhcNMzAwNzI4MTgw\n"
                                 "MTQ5WjBwMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEUMBIGA1UE\n"
                                 "BwwLU2FudGEgQ2xhcmExFzAVBgNVBAoMDldpLUZpIEFsbGlhbmNlMR0wGwYDVQQD\n"
                                 "DBRXRkEgUm9vdCBDZXJ0aWZpY2F0ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC\n"
                                 "AQoCggEBANp9wZirAd4/9rDd9L8fO8ysVA3cIBTBA3pfGlQvhSWjT/OhoKkP5Zr5\n"
                                 "yy4K0i+ujeP0xqUDNFnhzLDNb/5LjxWVaGaGu3TpPzjKqBJT4srsIGskNwkwzt2z\n"
                                 "IclGN4vy3/9kvIrozgZ7HAT8OKwXmXUTAD/4yw0AQv6ceFVcnNNtXsV9gJR4LU2j\n"
                                 "PtxK5bbzV7ABj/StJCfj55UF4Tu8iL08d3rJs2r7RnR13lRWziNUtGjOT6VVKTAT\n"
                                 "F60NZhQhp/fJ2FKizfpWTTP2TIXoBNy8JJUo+xUf9RO3mWmydKYNIqmfWY8r8O/A\n"
                                 "Ir4xfgVtauRtfeIR9hGYyE+wmx8sDuUCAwEAAaOBqzCBqDAdBgNVHQ4EFgQUrhjL\n"
                                 "sQJonLFV5x1AXxdPAtxLGq4wHwYDVR0jBBgwFoAUrhjLsQJonLFV5x1AXxdPAtxL\n"
                                 "Gq4wEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwQgYIKwYBBQUH\n"
                                 "AQEENjA0MDIGCCsGAQUFBzABhiZodHRwOi8vb2NzcC5yMi10ZXN0YmVkLndpLWZp\n"
                                 "Lm9yZzo4ODg4LzANBgkqhkiG9w0BAQsFAAOCAQEAVXYtlHbSsiDsIDvURStDqW/M\n"
                                 "izqNXYNgP/QVOxkEacvlOym1kZmyMJaKZsJXf+XxQ9wLmn5FH4wxcOu03Ln+7eV8\n"
                                 "DMp6QffRIaAkwbPj5hvDO6EvUXOSDNPT211axoutK91C4WgY9FM6rFZ9Rjm5fTx+\n"
                                 "LOI9yFDt+EVtKCJVZipNss9y2YqOcUfZ+albcWELPq7BvaseEFhK+RY2xmrhTkef\n"
                                 "OB83wBbnRo++COJN40xU7N09XsNsINEVPONDAjy9ilYIGiGtEo1habmRlfrz5QtL\n"
                                 "AWUmTuYWA5JJHBG9w9Lrruu/fsl4XSLvvAE7Mr+S3ata6DcajMmJcs+N9iHmbA==\n"
                                 "-----END CERTIFICATE-----\n"
                                 "-----BEGIN CERTIFICATE-----\n"
                                 "MIIEGjCCAwKgAwIBAgIUNJqZbmEwU+HDER28jLqWcB09dKAwDQYJKoZIhvcNAQEL\n"
                                 "BQAwcDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFDASBgNVBAcM\n"
                                 "C1NhbnRhIENsYXJhMRcwFQYDVQQKDA5XaS1GaSBBbGxpYW5jZTEdMBsGA1UEAwwU\n"
                                 "V0ZBIFJvb3QgQ2VydGlmaWNhdGUwHhcNMjAwNzMwMTgwMTQ5WhcNMzAwNzI4MTgw\n"
                                 "MTQ5WjBwMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEUMBIGA1UE\n"
                                 "BwwLU2FudGEgQ2xhcmExFzAVBgNVBAoMDldpLUZpIEFsbGlhbmNlMR0wGwYDVQQD\n"
                                 "DBRXRkEgUm9vdCBDZXJ0aWZpY2F0ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC\n"
                                 "AQoCggEBANp9wZirAd4/9rDd9L8fO8ysVA3cIBTBA3pfGlQvhSWjT/OhoKkP5Zr5\n"
                                 "yy4K0i+ujeP0xqUDNFnhzLDNb/5LjxWVaGaGu3TpPzjKqBJT4srsIGskNwkwzt2z\n"
                                 "IclGN4vy3/9kvIrozgZ7HAT8OKwXmXUTAD/4yw0AQv6ceFVcnNNtXsV9gJR4LU2j\n"
                                 "PtxK5bbzV7ABj/StJCfj55UF4Tu8iL08d3rJs2r7RnR13lRWziNUtGjOT6VVKTAT\n"
                                 "F60NZhQhp/fJ2FKizfpWTTP2TIXoBNy8JJUo+xUf9RO3mWmydKYNIqmfWY8r8O/A\n"
                                 "Ir4xfgVtauRtfeIR9hGYyE+wmx8sDuUCAwEAAaOBqzCBqDAdBgNVHQ4EFgQUrhjL\n"
                                 "sQJonLFV5x1AXxdPAtxLGq4wHwYDVR0jBBgwFoAUrhjLsQJonLFV5x1AXxdPAtxL\n"
                                 "Gq4wEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwQgYIKwYBBQUH\n"
                                 "AQEENjA0MDIGCCsGAQUFBzABhiZodHRwOi8vb2NzcC5yMi10ZXN0YmVkLndpLWZp\n"
                                 "Lm9yZzo4ODg4LzANBgkqhkiG9w0BAQsFAAOCAQEAVXYtlHbSsiDsIDvURStDqW/M\n"
                                 "izqNXYNgP/QVOxkEacvlOym1kZmyMJaKZsJXf+XxQ9wLmn5FH4wxcOu03Ln+7eV8\n"
                                 "DMp6QffRIaAkwbPj5hvDO6EvUXOSDNPT211axoutK91C4WgY9FM6rFZ9Rjm5fTx+\n"
                                 "LOI9yFDt+EVtKCJVZipNss9y2YqOcUfZ+albcWELPq7BvaseEFhK+RY2xmrhTkef\n"
                                 "OB83wBbnRo++COJN40xU7N09XsNsINEVPONDAjy9ilYIGiGtEo1habmRlfrz5QtL\n"
                                 "AWUmTuYWA5JJHBG9w9Lrruu/fsl4XSLvvAE7Mr+S3ata6DcajMmJcs+N9iHmbA==\n"
                                 "-----END CERTIFICATE-----\n";
